# Generated by Django 5.1.1 on 2024-09-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(max_length=80)),
                ('profession', models.CharField(max_length=40)),
                ('skills', models.CharField(max_length=90)),
                ('mobile_number', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
