# Generated by Django 5.1.1 on 2024-10-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriskill', '0002_forms_city_forms_country_forms_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='country',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='forms',
            name='mobile_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
