# Generated by Django 5.1.1 on 2024-10-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriskill', '0003_remove_forms_country_remove_forms_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='role',
            field=models.CharField(choices=[('landowner', 'Landowner'), ('skilled_professional', 'Skilled Professional')], default='skilled_professional', max_length=20),
        ),
    ]
