# Generated by Django 5.1.1 on 2024-10-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriskill', '0004_forms_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
