# Generated by Django 5.1.1 on 2024-10-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriskill', '0005_alter_forms_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='help_needed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='total_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
