# Generated by Django 5.1.1 on 2024-10-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriskill', '0006_forms_help_needed_forms_total_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forms',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
