# Generated by Django 5.1.1 on 2024-10-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriskill', '0011_landowner_skilledprofessional_delete_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='landowner',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skilledprofessional',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skilledprofessional',
            name='district',
            field=models.CharField(max_length=100),
        ),
    ]
