# Generated by Django 5.1.1 on 2024-10-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agriskill', '0014_alter_landowner_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skilledprofessional',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
